name: Build Embedded WebDAV Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    # 升级到 v4
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Prepare Artifacts
      run: |
        mkdir release_package
        copy build\Release\EmbeddedWebDavClient.exe release_package\
        xcopy lang release_package\lang\ /E /H /C /I

    # 升级到 v4，解决 GitHub Actions 报错问题
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WebDAV-Client-Windows
        path: release_package/